### ISSUE TITLE
Program seems to get stuck after connecting

### ISSUE THREAD

**Issue by kyleliamwalker** [oymotion/gForceSDKPython#4]
After selecting the device and establishing a connection, the menu never appears and the terminal remains in the same state - any ideas why this is?

**Comment by kyleliamwalker** [comment]
Seems to work the 1st time of running the script after booting up the system and then in the subsequent attempts fails to proceed after connecting - I'm also struggling to extract raw EMG data using these scripts.

**Comment by BigBro2014** [comment]
Thanks for your report. Please pull and try again.
