### ISSUE TITLE
Stuck in receiving emg data

### ISSUE THREAD

**Issue by armBray** [oymotion/gForceSDKPython#5]
I tried this code on a gForcePro+(3BB9) with the following setting:

GF.setDataNotifSwitch(DataNotifFlags['DNF_EMG_RAW'], set_cmd_cb, timeout = 2000)

and found two problems:
1. the bracialet send a packet lenght of 17 instead of 129 
2. after random cycles the bracialet seems that doesn't send datas anymore

**Comment by BigBro2014** [comment]
Fixed by replacing BLE lib.
